site_name: TorrentX
site_description: Minimal educational BitTorrent client in Java - docs and guides
site_url: 
repo_url: https://github.com/
repo_name: GitHub

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.tabs.link
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true

nav:
  - Overview: index.md
  - PART-1: Using Torrent File:
      - Overview: part-1/index.md
      - Stage 1: Bencode Decoding: part-1/stage-1-bencode.md
      - Stage 2: Torrent Parsing & Hashes: part-1/stage-2-torrent-parsing.md
      - Stage 3: Discover Peers & Handshake: part-1/stage-3-peers-handshake.md
      - Stage 4: Download Pieces & File: part-1/stage-4-download.md
  - PART-2: Using Magnet Links:
      - Overview: part-2/index.md
      - Stage 1: Parse Magnet & Announce: part-2/stage-1-magnet-parse.md
      - Stage 2: Extension Handshake: part-2/stage-2-ext-handshake.md
      - Stage 3: Request/Receive Metadata: part-2/stage-3-metadata.md
      - Stage 4: Download Pieces & File: part-2/stage-4-download.md
  - Installation & Usage: installation.md
