site_name: TorrentX
site_description: A minimal BitTorrent client in Java
site_url: https://<your-username>.github.io/TorrentX/
repo_url: https://github.com/<your-username>/TorrentX
site_dir: site
docs_dir: docs

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.follow
    - content.code.copy
    - content.tabs.link

nav:
  - Overview: index.md
  - Installation & Usage: install.md
  - Part 1: Using Torrent File:
      - Stage 1: part-1/stage-1.md
      - Stage 2: part-1/stage-2.md
      - Stage 3: part-1/stage-3.md
      - Stage 4: part-1/stage-4.md
  - Part 2: Using Magnet Links:
      - Stage 1: part-2/stage-1.md
      - Stage 2: part-2/stage-2.md
      - Stage 3: part-2/stage-3.md
      - Stage 4: part-2/stage-4.md

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - footnotes
  - codehilite
  - attr_list
  - def_list


