site_name: TorrentX
site_description: Minimal educational BitTorrent client in Java
site_url: https://kpraveenkumar19.github.io/TorrentX/
repo_url: https://github.com/kpraveenkumar19/TorrentX
theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - toc.integrate
    - content.code.copy
    - navigation.expand
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
nav:
  - Overview: index.md
  - Guide:
      - Stages: stages.md
      - Installation & Usage: install.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.tabbed
plugins:
  - search
  - mermaid2
extra:
  generator: false

